### ISSUE TITLE
compiling - pthreads and usage of -s parameter

### ISSUE THREAD

**Issue by colindaven** [DecodeGenetics/Ratatosk#1]
Hi, 

when compiling on Ubuntu 20.04, I'm not sure if pthreads were found or not ? At least, the test failed, but threads were found? Correct ? Is this to be expected ?

Thanks.
```

Release mode
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed   ************
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found   ************
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found  *************
-- Found Threads: TRUE  ************
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/ngsnfs/tools/Ratatosk/build
rcug@hpc06:/mnt/ngsnfs/tools/Ratatosk/build$
rcug@hpc06:/mnt/ngsnfs/tools/Ratatosk/build$
rcug@hpc06:/mnt/ngsnfs/tools/Ratatosk/build$ ldd `which tar` | grep pthread
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff6af5c7000)

```

**Comment by GuillaumeHolley** [comment]
Hey @colindaven,

I think this is rather normal: If Cmake had failed, the build files wouldn't have been generated at the end. The only way to know for sure is to compile the program after that with "make". If Pthread is missing, surely the linking step will fail or will tell you that some .so file is missing if you run "Ratatosk --help". Otherwise, you are good to go.

Guillaume

**Comment by colindaven** [comment]
Looks good, working so far. Thanks.

One further question - are illumina paired end reads supported, or do you just use read 1, or do you use a read combiner like flash to get combined single reads from pairs ?

Thanks

**Comment by GuillaumeHolley** [comment]
Illumina paired end reads are supported and the correction strongly benefit from the pairing (compared to reads which are not paired-end).
Mates from the same pair can be in the same input file or different ones, they just to need to have the same FASTA/FASTQ record title to be "recognized" as being from the same pair.

**Comment by colindaven** [comment]
Thanks, so will this pick them up (both R1 and R2 under -s param with full paths ?
srun -c 56 /mnt/ngsnfs/tools/Ratatosk/build/src/Ratatosk -s /lager2/rcug/2017/922E/iddm_R1.fastq.gz /lager2/rcug/2017/922E/iddm_R2.fastq.gz -l ../iddm_30kbp_3325_comb.fastq.gz -c 56 -o iddm_corr_ratatosk.fastq -v

Or is just specifying the R1 better ?

srun -c 56 /mnt/ngsnfs/tools/Ratatosk/build/src/Ratatosk -s /lager2/rcug/2017/922E/iddm_R1.fastq.gz -l ../iddm_30kbp_3325_comb.fastq.gz -c 56 -o iddm_corr_ratatosk.fastq -v

**Comment by GuillaumeHolley** [comment]
Use two times `-s`, e.g:
`srun -c 56 /mnt/ngsnfs/tools/Ratatosk/build/src/Ratatosk -s /lager2/rcug/2017/922E/iddm_R1.fastq.gz -s /lager2/rcug/2017/922E/iddm_R2.fastq.gz -l ../iddm_30kbp_3325_comb.fastq.gz -c 56 -o iddm_corr_ratatosk.fastq -v`

You can input as many input files as you want by using `-s` for each input file. Same applies to `-l`.
