### ISSUE TITLE
Resume from the last completed stage

### ISSUE THREAD

**Issue by lyrk50** [DecodeGenetics/Ratatosk#10]
Hi,
When I use the Ratatosk ,it may have terminated prematurely because out of RAM. The output is Ratatosk_sr.fasta and Ratatosk2.fasta. Is there any way to resume from the last completed stage?
lynn

**Comment by GuillaumeHolley** [comment]
Hi @lyrk50 ,

Unfortunately no, this is not possible  at the moment.

Guillaume
