### ISSUE TITLE
cant get a fastq output

### ISSUE THREAD

**Issue by HadrienRegue** [DecodeGenetics/Ratatosk#21]
Hi,

first, thanks for your software!

We have both sr paired end and single long ONT reads, so we want to try Ratatosk for our viral data:)
I've tried this command:
```
./Ratatosk \
    --in-short ILLUMINA/s01_R1.fastq.gz \
    --in-short ILLUMINA/s01_R2.fastq.gz  \
    --in-long  ONT/s01.fastq \
    --out-long BC01_test \
    --quality 0  \
    --cores 10
```
However I get a fasta output. After reading your documentation, -q option is mandatory to have a fastq output. I've tried the command above with --quality 0 or --quality or without, but the output is the same. Maybe I'm missing something.

Thanks,

Hadrien

**Comment by GuillaumeHolley** [comment]
Hi @HadrienRegue,

We are aware of the issue and it will be fixed in the next Ratatosk version for which FASTQ will be the default (and only) output format. In the meantime, could you try `--quality 1`? It means that all output bases with quality 0 are uncorrected bases.

Thanks
Guillaume

**Comment by HadrienRegue** [comment]
Hello again,

thanks to your tips, it seems to be working from now. There is still few barcodes to be proceed, but the corrected ones are indeed in fastq format.

Thanks:)
