### ISSUE TITLE
short reads for correction

### ISSUE THREAD

**Issue by PetrNguyen** [DecodeGenetics/Ratatosk#24]
Hi, I understand that if I am interested in SNPs, I should use both short and long reads for the same individual. But could I use short reads from another individual for purpose of de novo genome assembly? Could ratatosk be used for correcting long reads from pooled DNA samples? And should I somehow preprocessed the short reads prior to correction (trimming, filtering)? Thanks.

**Comment by GuillaumeHolley** [comment]
Hi @PetrNguyen,

I apologize for the delay, I missed the notification of your issue. Adapters should definitely be trimmed from the short reads before using them for correction. Filtering is up to you, it depends on what kind of filtering you want to do but I assume something rather minimal would do. When it comes to using short reads from individual A to correct the long reads from individual B, I would advise against using Ratatosk, even for mixed-haplotype assembly purposes. A lot of k-mers overlapping variants of individual B won't be found in the short reads of A, hence limiting the anchoring of long reads on the graph built from the short reads. The SNP candidate detection embedded within Ratatosk will be useless and will probably confuse the correction. Colors representing short reads mapping to the graph will guide the correction towards incorrect paths. And those are only issues coming on top of my head, there are many more smaller issues with using short/long reads from different individual. 

Guillaume
