### ISSUE TITLE
Reference-guided Ratatosk on Single Node with chromosomes but many unplaced scaffolds - faster with GNU Parallel?

### ISSUE THREAD

**Issue by jelber2** [DecodeGenetics/Ratatosk#25]
If one has a lot of bins (say >2000) because the reference genome has a lot of small scaffolds, but scaffold L50 is say ~10 (for a Hi-C chromosome scale mammalian genome with many, small unplaced scaffolds because original assembly was Illumina-based), would you recommend using the GNU Parallel implementation of the local reference guided correction code? I have been running Ratatosk_SingleNode.sh from commit 74ca617 with 30 cores, and I think it is about 1/3 way done after 1 day of computing. On that note, maybe you could provide a option for using GNU Parallel in a new commit of Ratatosk_SingleNode.sh through an if/elif statement. I understand that would certainly increase the memory usage.

**Comment by GuillaumeHolley** [comment]
Hi @jelber2,

The `Ratatosk_SingleNode.sh` script doesn't use GNU Parallel. Instead, each bin is corrected sequentially in this script but each bin correction is done in parallel. Given that you reference genome has a lot of small unplaced scaffold, I would advise against reference-based correction.

**Comment by jelber2** [comment]
Ok thanks!
