### ISSUE TITLE
Fastq input format for short reads

### ISSUE THREAD

**Issue by jianshu93** [DecodeGenetics/Ratatosk#28]
Hello Ratatosk Team,

I have short reads in 2 file 01_R1.fastq and 01_R2.fastq for example. How should I offer them to -s ? they have the same fastq sequence name (fastq header) for each sequence except -1 or -2 in the end of the fastq header. I do not see clear explanation.

Thanks,

Jianshu

**Comment by GuillaumeHolley** [comment]
Hi @jianshu93,

Reads from the same pair must have the same FASTA/FASTQ name to work with Ratatosk (first line of section `Usage` in the README). Hence, you must remove the `-1` or `-2` suffix from your FASTQ record headers. Off the top of my head, the following commands should do the trick:
```
awk '{LID=(NR-1)%4; if (LID==0) {print substr($0, 1, length($0)-2)} else {print $0}}' 01_R1.fastq > 01_R1_Ratatosk.fastq
awk '{LID=(NR-1)%4; if (LID==0) {print substr($0, 1, length($0)-2)} else {print $0}}' 01_R2.fastq > 01_R2_Ratatosk.fastq
```

Then, you can provide both files as input of Ratatosk using the `-s` argument (hence, `-s 01_R1_Ratatosk.fastq -s 01_R2_Ratatosk.fastq`).

Guillaume

**Comment by jianshu93** [comment]
Thank you that's really helpful. I can now run it successfully.

Jianshu
