### ISSUE TITLE
Installation typo & Docker

### ISSUE THREAD

**Issue by hoelzer** [DecodeGenetics/Ratatosk#30]
Hi all,

thanks for the tool! We are currently testing it in the context of a fungi hybrid assembly pipeline w/ various tools/polishers. 

One thing I noticed:

```
git clone --recursive https://github.com/DecodeGenetics/Ratatosk/Ratatosk.git
```

in the README should be

```
git clone --recursive https://github.com/DecodeGenetics/Ratatosk.git
```

and we also build a Docker container to easily integrate the tool into a (nextflow) pipeline. If you want to use the Container as well, it's here:

```
docker pull nanozoo/ratatosk:0.1--73685af
```
(I still need to test the container properly, but should work)

**Comment by GuillaumeHolley** [comment]
Hi @hoelzer,

Thank you for the typo (fixed) and the container, that's fantastic work! I'll try to test the container asap but I am mostly working on an air-gapped cluster so containers are a little bit tricky to use for me. We'll see how it goes.
Let me know how Ratatosk works for your assembly/polishing pipeline. As a short note, I am probably gonna push this week a new version that works better than the current one :)

Guillaume

**Comment by hoelzer** [comment]
Hi @GuillaumeHolley ah that's great to hear! I can then easily set up a new container with that version :) 

We also just tested the container in our pipeline: seems to work all fine!

Cheers,
Martin
