### ISSUE TITLE
Input file format

### ISSUE THREAD

**Issue by OZTaekOppa** [DecodeGenetics/Ratatosk#31]
Hi,

Thank you for the great program.
Just want to make sure about the input format.
Based on the manual, it is recommended to use Illumina PE reads to correct PacBio or ONT reads.
Given the circumstances, not sure which input file format would be appropriate. 
1. Ratatosk correct -v -c 16 -s short_read_R1.fastq  -s short_read_R2.fastq -l long_reads.fastq -o out_long_reads
2. Ratatosk correct -v -c 16 -s short_read_R12all.fastq -l long_reads.fastq -o out_long_reads
--> -s short_read_R12all.fastq: It means to make a single input file from the same PE reads.

Any suggestion?

Cheers

**Comment by GuillaumeHolley** [comment]
Hi @OZTaekOppa,

Thank you for your interest in Ratatosk. Both suggestions are good and are the same for Ratatosk so use whichever is the most convenient for you. As a short reminder, Ratatosk recognizes mates from the same pair as reads with the same name/title. If the two mates from the same pair do not have exactly the same name/title, they will both be interpreted as two separate single-end reads. 

Guillaume
