### ISSUE TITLE
Treated as HiFi or PacBio Raw

### ISSUE THREAD

**Issue by OZTaekOppa** [DecodeGenetics/Ratatosk#32]
Hi,

I have four more questions.

FYI, a single memory node approach on a PBSpro environment. 
module load ratatosk/0.1-foss-2020b
Script: Ratatosk correct -v -c 16 -s /home/SL_Reads_R12All.fq.gz -l /home/SLPBONT1st.fasta -o out_long_RataSLPBONT1st

Q1. Memory issue: I tested a diploid genome (2n=0.7Gb) and took 340 hrs (walltime) with 180G memory and 16 CPUs. Is it normal?

Q2. HiFi or PacBio Raw: Can the corrected PacBio raw read be treated as PacBio HiFi (or corrected) for genome assemblies (e.g. CANU and Flye) after completing the Ratatosk correction? Or, should it be the same as PacBio raw read for genome assemblies?

Q3. I am also testing the multiple nodes de novo correction. After reading the manual, I am trying to have 4 rounds of correction (-r 4). However, the -r option was not recognised via "Ratatosk_denovo_SLURM.sh". What other option do I have? Can I re-run the "Ratatosk_denovo_SLURM.sh" four times with each round output (corrected reads) for next round input? 

Q4.  Error Ratatosk_denovo_SLURM.sh: I have also tried this script on a PBS pro environment but there was no luck. The script could not find the "sbatch" command. Any suggestion for this matter? 

Executed script:
module load ratatosk/0.1-foss-2020b
bash /work/Ratatosk/Ratatosk_denovo_SLURM.sh -c 6 -C 14 -n 6 -s /home/JulGFe_R12All.fastq.gz -l /home/JGFPB_1A.fasta.gz -o out_long_RJGFe4R

Error: 
Minimum number of threads: 6
Maximum number of threads: 14
Maximum number of nodes: 6
Input short read file: /home/JulGFe_R12All.fastq.gz
Input long read file: /home/JGFPB_1A.fasta.gz
Output prefix: /work/Rata4R_Multi/out_long_RJGFe4R
Slurm partition: nomosix
/work/Ratatosk/Ratatosk_denovo_SLURM.sh: line 150: sbatch: command not found
Job(s) submission failed.

PBS Job 9745287.pbs
CPU time  : 00:10:05
Wall time : 00:11:15
Mem usage : 29980936kb

Many thanks all the time!

**Comment by GuillaumeHolley** [comment]
Dear @OZTaekOppa,

I apologize for the delay.

1. Unfortunately, this is probably normal. Memory taken by Ratatosk is proportional to the Illumina coverage while time taken is proportional to the ONT coverage. So even though your genome is only 0.7 Gbp, if the coverage of your input reads is high, Ratatosk will take quite a bit of time to process it all. That being said, I just pushed Ratatosk v0.7 which should be a lot faster and more accuratre that the version you tried.
2. I cannot speak for CANU as I haven't tried it myself but for human, you can use Flye in `--pacbio-hifi` mode with Ratatosk corrected reads. Flye v2.9 has now a `--nano-hq` mode for high quality ONT reads that is probably more adapted.
3.  `-r` option is not included so far in the script `Ratatosk_denovo_SLURM.sh` and you cannot run the 4 rounds of correction separately. I'll put this on my todo list for the next push.
4. PBS Pro is a different scheduling system than SLURM so none of the scripts provided for multi-nodes correction will work on your cluster. However, it seems rather easy to migrate a SLURM script to a PBS Pro script, see [here](https://support.pawsey.org.au/documentation/display/US/Migrating+from+PBS+Pro+to+SLURM) and [here](https://portal.supercomputing.wales/index.php/index/slurm/pbs-pro-to-slurm-very-quick-reference/). I would welcome any PR if you get something working.
