### ISSUE TITLE
how to create a single short read file 

### ISSUE THREAD

**Issue by gunjanpandey** [DecodeGenetics/Ratatosk#33]
How to create a single short read file as an input from two  Illumina paired end (trimmed and validated - trimgalore output) files?

**Comment by GuillaumeHolley** [comment]
Hi @gunjanpandey,

First of all, I wanted to make sure you know you can input your 2 files in Ratatosk without merging them. Just use `-s file1.fastq -s file2.fastq`.

if you still want to merge, the only rule regarding PE-reads is that records from the same pair (in your case, one record in each file) must have exactly the same record name. I imagine here that your 2 files are ordered so in that case, just look at the first line of each file and make sure they are exactly the same. If they are, just concatenate the two files, `cat file1.fastq file2.fastq > file3.fastq`.

**Comment by gunjanpandey** [comment]
Thanks for your reply. Could you please clarify on the point below?

**Ratatosk works best with paired-end short reads in input (-s): reads from the same pair must have the same FASTA/FASTQ name** 

Is `-s illu_R1.fastq -s illu_R2.fastq` the right way to provide paired illumina data?

**Comment by GuillaumeHolley** [comment]
Hi @gunjanpandey,

It is exactly what I wrote in my first response: 

> First of all, I wanted to make sure you know you can input your 2 files in Ratatosk without merging them. Just use `-s file1.fastq -s file2.fastq`.

So yes, `-s illu_R1.fastq -s illu_R2.fastq` should work just fine. Just make sure the first line of each file is *exactly* the same.

**Comment by Akazhiel** [comment]
Hi @GuillaumeHolley,

When you say **exactly** the same name, does this mean the reads from `file1.fastq` and `file2.fastq` can't end in `/1` and `/2` respectively or the program ignores this?

Best regards,

Jonatan

**Comment by GuillaumeHolley** [comment]
Hi @Akazhiel,

You are correct: it means that the reads from `file1.fastq` and `file2.fastq` can't end in `/1` and `/2` respectively. I'm probably going to change this in the next version.

Guillaume
