### ISSUE TITLE
-i or -s?

### ISSUE THREAD

**Issue by hbeale** [DecodeGenetics/Ratatosk#37]
There’s a discrepancy in the first command line example and explanatory paragraph. 

Paragraph is: 
Ratatosk corrects (Ratatosk correct) the long read file (-l in_long_reads.fastq) with 16 threads (-c 16) using an index built from the short read file (-i short_reads.fastq).

but example command uses -s short_reads.fastq

really looking forward to trying Ratatosk out!

**Comment by GuillaumeHolley** [comment]
Hi @hbeale,

Thank you for noticing this issue, I have just updated the README with the right option (`-s` and not `-i`).

Guillaume
