### ISSUE TITLE
questions re index construction & insert size

### ISSUE THREAD

**Issue by rwhetten** [DecodeGenetics/Ratatosk#42]
Thanks for a great tool! I have two questions to try to optimize my use of Ratatosk. 
1. For the insert size, how sensitive is the error-correction process to deviation from the default 500-bp insert size? In other words, if median insert size is 450 bp, is it useful to change that parameter? If inserts are greatly different from 500 bp (e.g. 250 bp), does setting the correct insert size using -i improve the outcome?
2. I'm working with a large genome (>15 Gb haploid size), and plan to error-correct several lanes of PromethION data. Is it possible to build an index from the short-read data (39x coverage) once and use the same index to correct each lane of nanopore reads? Or is the process of building the index dependent on the long-read data, so that a new index must be made for each long-read dataset processed?

**Comment by GuillaumeHolley** [comment]
Hi @rwhetten,

- You can deviate a little bit from the default value of that parameter, ideally using 1/ the exact median value, 2/ a value greater or 3/ a value lower (in that order of preference). The difference between 2/ and 3/ is that by using 2/, Ratatosk might pick up a little bit too much "signal" which I think in general is better than not enough. 
In your case, median insert is 450 bp and default `-i` is 500bp so I wouldn't bother changing the default value of `-i`. However, in the case of 250bp median insert and default `-i 500`, Ratatosk would definitely pick way too much signal which might confuse it so I would change the default value of `-i`. To summarize, changing `-i` is unlikely to impact the outcome for small deviations but will most definitely have a negative impact for larger deviations.

- Yes and no. What I think you need here is the [4 commands correction of Ratatosk](https://github.com/DecodeGenetics/Ratatosk#single-compute-node---four-steps): 
1. The first command (`index -1`) builds the index for all the short read data you have, irrespective of the long reads in input.
2. You can use that index in the second command (`correct -1`) to correct each flowcell separately/in parallel.
3. For the 3rd command (`index -2`), you have to use in input all the corrected flowcells from the second command.
4. You can run the 4th command in parallel for each corrected flowcell from `correct -1` using the index from `index -2`. Do not use the `-L` option in this case.

I hope this is clear enough :)
Guillaume

**Comment by rwhetten** [comment]
Yes, that is perfect - thank you for the quick reply! I'll close the issue.
